#!/bin/sh

# git-conventional-commits is installed via npm in this repo. Run npm ci to install
# use git-conventional-commits, see https://github.com/qoomon/git-conventional-commits
npx git-conventional-commits commit-msg-hook "$1"